export const endpoint =
  import.meta.env.VITE_APP_USE_MOCK_SERVER === 'true'
    ? import.meta.env.VITE_APP_MOCK_API_ENDPOINT
    : import.meta.env.VITE_APP_API_ENDPOINT;

export const categoryTable = new Map([
  ['ui', 'UI'],
  ['design', 'デザイン（Design）'],
  ['react', 'React'],
  ['github', 'GitHub'],
  ['javascript', 'JavaScript'],
  ['rails', 'Rails'],
  ['aws', 'AWS'],
  ['docker', 'Docker'],
  ['terraform', 'Terraform'],
  ['nuxtjs', 'Nuxt.js'],
  ['game', 'ゲーム'],
  ['まとめ', 'まとめ'],
  ['vue', 'Vue.js'],
  ['netlify', 'Netlify'],
  ['gatsby', 'Gatsby'],
  ['graphql', 'GraphQL'],
  ['php', 'PHP'],
  ['flutter', 'Flutter'],
  ['heroku', 'Heroku'],
  ['nestjs', 'NestJS'],
  ['python', 'Python'],
  ['スタートアップ', 'スタートアップ'],
  ['ruby', 'Ruby'],
  ['bot', 'bot'],
  ['googlemapsapi', 'GoogleMapsAPI'],
  ['gas', 'GAS'],
  ['ポエム', 'ポエム'],
  ['nextjs', 'Next.js'],
  ['vercel', 'Vercel'],
  ['chrome', 'Chrome拡張'],
  ['svg', 'SVG'],
  ['typescript', 'TypeScript'],
  ['django', 'Django'],
  ['gcp', 'GCP'],
  ['laravel', 'Laravel'],
  ['機械学習', '機械学習'],
  ['firebase', 'Firebase'],
  ['nodejs', 'Node.js'],
  ['英語', '英語'],
  ['失敗談', '失敗談'],
  ['swift', 'Swift'],
  ['アイデア', 'アイデア'],
  ['csharp', 'C#'],
  ['azure', 'Azure'],
  ['jquery', 'jQuery'],
  ['unity', 'Unity'],
  ['marketing', 'マーケティング'],
  ['pwa', 'PWA'],
  ['circleci', 'CircleCI'],
  ['twitter', 'Twitter'],
  ['css', 'CSS'],
  ['amplify', 'Amplify'],
  ['fargate', 'Fargate'],
  ['ecs', 'ECS'],
  ['nocode', 'ノーコード'],
  ['android', 'Android'],
  ['springboot', 'SpringBoot'],
  ['mysql', 'MySQL'],
  ['ios', 'iOS'],
  ['firestore', 'Firestore'],
  ['go', 'Go'],
  ['threejs', 'three.js'],
  ['stripe', 'Stripe'],
  ['others', 'その他'],
  ['line', 'LINE'],
  ['supabase', 'Supabase'],
  ['cloudflare', 'Cloudflare'],
  ['rust', 'Rust'],
  ['wasm', 'WebAssembly'],
  ['auth0', 'Auth0'],
  ['prisma', 'Prisma'],
  ['svelte', 'Svelte'],
  ['html', 'HTML'],
  ['slack', 'Slack'],
]);

export const languageCategories = [
  'javascript',
  'php',
  'ruby',
  'typescript',
  'python',
  'nodejs',
  'csharp',
  'unity',
  'go',
  'rust',
  'wasm',
];

export const frameworkCategories = [
  'react',
  'rails',
  'nuxtjs',
  'vue',
  'gatsby',
  'flutter',
  'nextjs',
  'nestjs',
  'django',
  'laravel',
  'swift',
  'jquery',
  'springboot',
  'threejs',
  'svelte',
];

export const databaseCategories = ['mysql', 'firestore', 'prisma'];

export const infraCategories = [
  'aws',
  'terraform',
  'netlify',
  'heroku',
  'vercel',
  'gcp',
  'azure',
  'amplify',
  'fargate',
  'ecs',
];

export const platformCategories = [
  'firebase',
  'supabase',
  'cloudflare',
  'ios',
  'android',
];

export const toolsCategories = [
  'github',
  'docker',
  'bot',
  'googlemapsapi',
  'gas',
  'pwa',
  'chrome',
  'circleci',
  'twitter',
  'nocode',
  'stripe',
  'line',
  'auth0',
  'slack',
  '機械学習',
];

export const otherCategories = [
  'others',
  'ポエム',
  'まとめ',
  'design',
  'ui',
  'html',
  'css',
  'game',
  'graphql',
  'アイデア',
  'marketing',
  '英語',
  '失敗談',
  'svg',
  'スタートアップ',
];
